pipelines:
  branches: # Branch-specific pipelines definitions
    master:
      - step:
          name: Build and test the app
          image: node:latest
          script:
            - npm install
            - npm run test
            - npm run build
  custom: # Pipeline that only runs manually
    production:
      - step:
          name: Building the app
          image: node:latest
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploying the app to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:1.1.0 # https://bitbucket.org/atlassian/aws-s3-deploy
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                ACL: "public-read-write" # https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl
                LOCAL_PATH: "build"
